[[intro]]
== Introduction

The Sstdso extension standardises a mechanism that allows system software to dynamically switch individual harts between RVWMO and RVTSO semantics.

This mechanism is intended for systems that:

* want to provide RVTSO semantics for individual user-space processes or virtualized guest operating systems,
* can dynamically switch the U, VS, and VU execution on harts between RVWMO and RVTSO semantics,
* natively prefer (e.g., for performance reasons) to operate with RVWMO semantics.

=== Interoperability between RVTSO and RVWMO

RVTSO makes the following adjustments to RVWMO:

* All load operations behave as if they have an acquire-RCpc annotation.
* All store operations behave as if they have a release-RCpc annotation.
* All AMOs behave as if they have both acquire-RCsc and release-RCsc annotations.

This makes all rules for preserved program order redundant, except those for explicit synchronization.

For the interoperability between code concurrently executing under RVTSO and RVWMO rules (on separate harts), we can therefore assume correct interoperability without any special precautions if the processes use explicit synchronization primitives (and RCpc annotations for the processes executing under RVWMO semantics) as required for their respective memory consistency models.

=== Suitability for the Fast-Track Extension Process

This proposed extension meets the Fast Track criteria:

* it is self-contained with a programming-model consisting of bit-assignments in CSRs,
* it provides a mechanism that will be used by privileged-level software only
* it composes with the existing RISC-V instruction set, and
* it is not expected to be contentious.

